springdoc:
  api-docs:
    path: /api/doc
  swagger-ui:
    path: /api
  packages-to-scan: tw.edu.ntub.imd.courtesyumbrella.controller
  default-produces-media-type: application/json;charset=UTF-8
spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  profiles:
    active: local
  security:
    jwt:
      secret: \$2a\$10\$y/KQjTKFpJsCG6wCAiEW5uFfyPotF4kLE2kOWwLSgJjjuhLJRTNZW
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${courtesy-umbrella.database.url}
    username: ${courtesy-umbrella.database.account}
    password: ${courtesy-umbrella.database.password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: ${spring.jpa.database-platform}
        hbm2ddl:
          auto: ${spring.jpa.hibernate.ddl-auto}
        show_sql: ${spring.jpa.show-sql}
        format_sql: ${spring.jpa.show-sql}
server:
  port: 8080
  servlet:
    context-path: /
  image:
    url: http://${server.ip}:${server.port}${server.context-path}${server.image.name}
  file:
    url: http://${server.ip}:${server.port}${server.context-path}${server.file.name}
logging:
  config: classpath:log4j2.yml
  level:
    jdbc:
      sqlonly: OFF
      audit: OFF
      resultset: OFF
      connection: OFF
