server:
  ip: 211.75.1.201
  image:
    name: image
    path: C:${file.separator}UploadFile${file.separator}${server.image.name}${file.separator}
  file:
    name: file
    path: C:${file.separator}UploadFile${file.separator}${server.file.name}${file.separator}
logging:
  level:
    sqltiming: OFF
    resultsettable: OFF
