spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  profiles:
    active: local
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${courtesy-umbrella.database.url}
    username: ${courtesy-umbrella.database.account}
    password: ${courtesy-umbrella.database.password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: ${spring.jpa.database-platform}
        hbm2ddl:
          auto: none
        show_sql: false
        format_sql: false
server:
  port: 8080
  servlet:
    context-path: /
  image:
    url: http://${server.ip}:${server.port}${server.context-path}image
  file:
    url: http://${server.ip}:${server.port}${server.context-path}file
